//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LKE_LoginEntities : DbContext
    {
        public LKE_LoginEntities()
            : base("name=LKE_LoginEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogInHistory> LogInHistories { get; set; }
        public virtual DbSet<UserActionTrack> UserActionTracks { get; set; }
        public virtual DbSet<WebDatabas> WebDatabases { get; set; }
        public virtual DbSet<WebDbaseAssignment> WebDbaseAssignments { get; set; }
        public virtual DbSet<WebRoleDesc> WebRoleDescs { get; set; }
        public virtual DbSet<WebRole> WebRoles { get; set; }
        public virtual DbSet<WebUser> WebUsers { get; set; }
        public virtual DbSet<WebUserHistory> WebUserHistories { get; set; }
        public virtual DbSet<zzzInitialCatalog> zzzInitialCatalogs { get; set; }
        public virtual DbSet<zzzWebImport_Purchases> zzzWebImport_Purchases { get; set; }
        public virtual DbSet<zzzWebUser_BkupOrig> zzzWebUser_BkupOrig { get; set; }
        public virtual DbSet<ReportsArchive> ReportsArchives { get; set; }
    
        public virtual ObjectResult<GetAdminAllUsers_Result> GetAdminAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminAllUsers_Result>("GetAdminAllUsers");
        }
    
        public virtual ObjectResult<string> IS_001_GetDbaseList(string userName, string userPassword)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("IS_001_GetDbaseList", userNameParameter, userPasswordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LockUnlockUser(Nullable<int> wuid, string isLocked)
        {
            var wuidParameter = wuid.HasValue ?
                new ObjectParameter("wuid", wuid) :
                new ObjectParameter("wuid", typeof(int));
    
            var isLockedParameter = isLocked != null ?
                new ObjectParameter("isLocked", isLocked) :
                new ObjectParameter("isLocked", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LockUnlockUser", wuidParameter, isLockedParameter);
        }
    }
}
