//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsArchive
    {
        public int ID { get; set; }
        public int UserActionID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string ReportName { get; set; }
        public string Username { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> CaseID2 { get; set; }
        public Nullable<int> LEID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Dep_Type { get; set; }
        public string BlobName { get; set; }
        public string ContainerName { get; set; }
        public Nullable<int> generationStatus { get; set; }
    
        public virtual UserActionTrack UserActionTrack { get; set; }
    }
}
