//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActionTrack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserActionTrack()
        {
            this.ReportsArchives = new HashSet<ReportsArchive>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsStarted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string CreatedFilePath { get; set; }
        public string Database { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ReportIDShortNames { get; set; }
        public string NotificationText { get; set; }
        public Nullable<bool> IsRequestRecreation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportsArchive> ReportsArchives { get; set; }
    }
}
