//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDbaseAssignment
    {
        public int UserID { get; set; }
        public int DbaseID { get; set; }
        public int ID { get; set; }
    
        public virtual WebDatabas WebDatabas { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}
