//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebDatabas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebDatabas()
        {
            this.WebDbaseAssignments = new HashSet<WebDbaseAssignment>();
        }
    
        public int ID { get; set; }
        public string GenericDbaseName { get; set; }
        public string ActualDbaseName { get; set; }
        public Nullable<byte> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebDbaseAssignment> WebDbaseAssignments { get; set; }
    }
}
