//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRole
    {
        public Nullable<int> WebUserID { get; set; }
        public Nullable<int> InitialCatalogID { get; set; }
        public string Role { get; set; }
        public int ID { get; set; }
    
        public virtual WebRoleDesc WebRoleDesc { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}
