//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUserHistory
    {
        public int WUhid { get; set; }
        public Nullable<int> ID { get; set; }
        public string WebUserName { get; set; }
        public string WebUserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Inactive { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
