//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebUser()
        {
            this.WebDbaseAssignments = new HashSet<WebDbaseAssignment>();
            this.WebRoles = new HashSet<WebRole>();
        }
    
        public int ID { get; set; }
        public string WebUserName { get; set; }
        public string WebUserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string IsLocked { get; set; }
        public string LastLogin { get; set; }
        public string RetryCount { get; set; }
        public Nullable<System.DateTime> PasswordUpdatedOn { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public string Email { get; set; }
        public Nullable<long> Phone { get; set; }
        public string User_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebDbaseAssignment> WebDbaseAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebRole> WebRoles { get; set; }
    }
}
