//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKE_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzzWebImport_Purchases
    {
        public string Entity { get; set; }
        public string AssetID { get; set; }
        public string AssetManu { get; set; }
        public string AssetModel { get; set; }
        public string AssetCategory { get; set; }
        public string AssetDescr { get; set; }
        public Nullable<byte> AssetType { get; set; }
        public Nullable<byte> LKEEligible_Purchase { get; set; }
        public string AcqDate { get; set; }
        public string BuyerName { get; set; }
        public string CtryRQAsset { get; set; }
        public string StRQAsset { get; set; }
        public string Currency { get; set; }
        public string For_Dom { get; set; }
        public string PONum { get; set; }
        public Nullable<byte> NeworUsed { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> CaseID2 { get; set; }
        public Nullable<int> LEID { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> RelatedPartyPurchase { get; set; }
        public string DateAssetAdded { get; set; }
        public string AssedAddedby { get; set; }
        public Nullable<double> Actual_ConstructiveReceipt { get; set; }
        public string OptFld_Varchar1 { get; set; }
        public string OptFld_Varchar2 { get; set; }
        public string OptFld_Varchar3 { get; set; }
        public string OptFld_Varchar4 { get; set; }
        public string OptFld_Varchar5 { get; set; }
        public string OptFld_Varchar6 { get; set; }
        public string OptFld_Varchar7 { get; set; }
        public string OptFld_Varchar8 { get; set; }
        public string OptFld_Varchar9 { get; set; }
        public string OptFld_Varchar10 { get; set; }
        public Nullable<int> OptFld_Integer1 { get; set; }
        public Nullable<int> OptFld_Integer2 { get; set; }
        public Nullable<int> OptFld_Integer3 { get; set; }
        public Nullable<int> OptFld_Integer4 { get; set; }
        public Nullable<int> OptFld_Integer5 { get; set; }
        public Nullable<int> OptFld_Integer6 { get; set; }
        public Nullable<int> OptFld_Integer7 { get; set; }
        public Nullable<int> OptFld_Integer8 { get; set; }
        public Nullable<int> OptFld_Integer9 { get; set; }
        public Nullable<int> OptFld_Integer10 { get; set; }
        public Nullable<double> AcqCost { get; set; }
        public Nullable<double> BootReceived { get; set; }
        public Nullable<double> ActConsReceipt { get; set; }
        public Nullable<byte> BonusDepCde { get; set; }
        public Nullable<byte> Depreciate { get; set; }
        public Nullable<double> DepreciableLife { get; set; }
        public string Convention { get; set; }
        public string Method { get; set; }
        public string Dep_Type { get; set; }
        public string DepTbl { get; set; }
        public Nullable<double> ResidualValue { get; set; }
        public Nullable<byte> UseResidualValue { get; set; }
        public string ParentAssetID { get; set; }
        public Nullable<double> OptFld_Float1 { get; set; }
        public Nullable<double> OptFld_Float2 { get; set; }
        public Nullable<double> OptFld_Float3 { get; set; }
        public Nullable<double> OptFld_Float4 { get; set; }
        public Nullable<double> OptFld_Float5 { get; set; }
        public Nullable<double> OptFld_Float6 { get; set; }
        public Nullable<double> OptFld_Float7 { get; set; }
        public Nullable<double> OptFld_Float8 { get; set; }
        public Nullable<double> OptFld_Float9 { get; set; }
        public Nullable<double> OptFld_Float10 { get; set; }
        public Nullable<System.DateTime> PISDate { get; set; }
        public Nullable<double> LiabilityAssumed { get; set; }
        public Nullable<double> FedAccumDep { get; set; }
        public Nullable<double> FedAccumMonths { get; set; }
        public Nullable<double> AmtAccumDep { get; set; }
        public Nullable<double> AmtAccumMonths { get; set; }
        public Nullable<double> Method3AccumDep { get; set; }
        public Nullable<double> Method3AccumMonths { get; set; }
        public Nullable<double> Method4AccumDep { get; set; }
        public Nullable<double> Method4AccumMonths { get; set; }
        public Nullable<double> Method5AccumDep { get; set; }
        public Nullable<double> Method5AccumMonths { get; set; }
        public int zzzWebImport_PurchasesID { get; set; }
        public string OptFld_Varchar11 { get; set; }
        public string OptFld_Varchar12 { get; set; }
        public string OptFld_Varchar13 { get; set; }
        public string OptFld_Varchar14 { get; set; }
        public string OptFld_Varchar15 { get; set; }
        public string OptFld_Varchar16 { get; set; }
        public string OptFld_Varchar17 { get; set; }
        public string OptFld_Varchar18 { get; set; }
        public string OptFld_Varchar19 { get; set; }
        public string OptFld_Varchar20 { get; set; }
        public string OptFld_Varchar21 { get; set; }
    }
}
